# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true

# Project
version=1.0.0
group=com.github.litermc.cosmicpluse
java_version=17

# Common
minecraft_version=1.20.1
mod_name=CosmicPluse
mod_author=zyxkad
mod_id=cosmicpluse
modrinth_project_id=
license=GPL-3.0
credits=
description=A laser mod for Minecraft
github_repo=https://github.com/LiterMC/CosmicPluse
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.92.6+1.20.1

# Forge
forge_version=47.4.0
forge_loader_version_range=[47,)

# Hard dependencies
architectury_version=9.1.12
cloth_config_version=6.4.90
kff_version=4.10.0
veil_version=1.0.0.239
vs2_version=2.3.0-beta.11
vs_core_version=1.1.0+a5203f1d01

# Soft dependencies
cct_version=1.116.2
cosmos_version=0.0.7.2
create_fabric_version=6.0.8.0+build.1734-mc1.20.1
create_version=6.0.8-289
jade_version=11.13.1
starlance_version=1.5.0

mod_artifact_suffix=
